name:                displace
version:             0.1.0.0
github:              "ilikeavocadoes/displace"
license:             OtherLicense
author:              "ilikeavocadoes"
maintainer:          "ilikeavocadoes@hush.com"
copyright:           "2019 ilikeavocadoes"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/displace#readme>

dependencies:
- base >= 4.7 && < 5
- yaml >= 0.11 && < 0.12
- attoparsec >= 0.13.2.2 && < 0.14
- text
- containers

library:
  source-dirs: src

executables:
  displace-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - displace
