name:                displace
version:             0.1.0.1
github:              "ilikeavocadoes/displace"
license:             OtherLicense
author:              "Lassi Haasio"
maintainer:          "Lassi Haasio"
copyright:           "2019 Lassi Haasio"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/ilikeavocadoes/displace#readme>

dependencies:
- base >= 4.7 && < 5
- yaml >= 0.11 && < 0.12
- text
- containers
- unordered-containers
- regex-tdfa
- regex-tdfa-text
- pandoc-types

library:
  source-dirs: src

executables:
  displace:
    main: Main.hs
    source-dirs: standalone
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - displace
  pandoc-displace:
    main: Main.hs
    source-dirs: filter
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - displace
